steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t' ,'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}', '.']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}']

substitutions:
   _ARTIFACT_REGISTRY_REPO: samplerepo
   _IMAGE_NAME: gcpdevops
options:
   substitution_option: 'ALLOW_LOOSE'
