steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t' ,'gcr.io/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${IMAGE_NAME}', '.']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${IMAGE_NAME}']

substitutions:
   _ARTIFACT_REGISTRY_REPO: samplerepo
   _IMAGE_NAME: gcpdevops
options:
   substitution_option: 'ALLOW_LOOSE'
