steps:
 - name: python
   entrypoint: '/bin/bash'
   args: 
     - '-c'
     - 'pip install virtualenv && virtualenv /workspace/venv'
     - '--user'

 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bin/bash'
   args: ['-c', 'echo Username=$$MY_SEC']
   secretEnv: ['MY_SEC']
      
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t' ,'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}', '.']

 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}']

substitutions:
   _ARTIFACT_REGISTRY_REPO: samplerepo
   _IMAGE_NAME: gcpdevops
options:
   substitution_option: 'ALLOW_LOOSE'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/my-secret/versions/1
    env: 'MY_SEC'
