apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: gcp-devops-gke
        image: nginx:1.14.2
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"

---
apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-service
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
    selector:
      app: flask
  type: 'LoadBalancer'
